[application]
name = "biyard-landing"

[web.app]
title = "Biyard - Blockchain Launchpad Platform"

[web.resource]
style = []
script = ["https://cdn.tailwindcss.com"]

[web.resource.dev]
style = []
script = ["https://cdn.tailwindcss.com"]
