name: Dev deploy

on:
  push:
    branches:
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.0 --activate

      - name: Deploy to S3
        env:
          ENV: dev
        run: |
          make sync-landing


      - name: Prepare artifacts
        run: |
          tar czvf landing-dist.tar.gz landing/dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: landing-web-${{ github.sha }}
          path: ${{ github.workspace }}/landing-dist.tar.gz
          if-no-files-found: error
          retention-days: 7

  console:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.0 --activate

      - name: Deploy to S3
        env:
          ENV: dev
        run: |
          make sync-console


      - name: Prepare artifacts
        run: |
          tar czvf console-dist.tar.gz console/dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: console-web-${{ github.sha }}
          path: ${{ github.workspace }}/console-dist.tar.gz
          if-no-files-found: error
          retention-days: 7

  create-release-pr:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    needs: [web, console]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}
      - name: Git pr release action
        uses: grassedge/git-pr-release-action@v1.0
        with:
          base: main
          head: dev
          token: ${{ secrets.GITHUB_TOKEN }}
