name: Dev deploy

on:
  push:
    branches:
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  landing:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: landing-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: stable
          targets: wasm32-unknown-unknown
          cache: false

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "landing-build"

      - uses: cargo-bins/cargo-binstall@main

      - name: Install Dioxus CLI
        run: cargo binstall dioxus-cli --force

      - name: Build Landing (Lambda)
        working-directory: landing
        env:
          ENV: dev
        run: |
          npm i -D tailwindcss
          make build-lambda

      - name: Build and push Docker image
        working-directory: landing
        env:
          ENV: dev
          ECR: ${{ steps.landing-ecr.outputs.registry }}/biyard/landing
        run: |
          make docker
          make docker.push

      - name: Deploy static assets to S3
        env:
          ENV: dev
        run: |
          make sync-landing

  console:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: stable
          targets: wasm32-unknown-unknown
          cache: false

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "console-build"

      - uses: cargo-bins/cargo-binstall@main

      - name: Install Dioxus CLI
        run: cargo binstall dioxus-cli --force

      - name: Build Dioxus console app
        working-directory: console
        env:
          ENV: dev
          DYNAMO_TABLE_PREFIX: biyard-dev
        run: make build

      - name: Build and push Docker image
        working-directory: console
        env:
          ENV: dev
        run: |
          make docker.login
          make docker
          make docker.push

  deploy:
    runs-on: ubuntu-latest
    needs: [landing, console]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy
        env:
          ENV: dev
          REGION: ap-northeast-2
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOMAIN: dev.biyard.co
        run: |
          npm i -g aws-cdk
          make deploy

  create-release-pr:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    needs: [deploy]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}
      - name: Git pr release action
        uses: grassedge/git-pr-release-action@v1.0
        with:
          base: main
          head: dev
          token: ${{ secrets.GITHUB_TOKEN }}
