name: Dev deploy

on:
  push:
    branches:
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.0 --activate

      - name: Deploy to S3
        env:
          ENV: dev
          VITE_API_BASE_URL: https://api.dev.biyard.co
        run: |
          make sync-landing

      - name: Prepare artifacts
        run: |
          tar czvf landing-dist.tar.gz landing/dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: landing-web-${{ github.sha }}
          path: ${{ github.workspace }}/landing-dist.tar.gz
          if-no-files-found: error
          retention-days: 7

  console:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.0 --activate

      - name: Deploy to S3
        env:
          ENV: dev
          API_URL: https://api.dev.biyard.co
        run: |
          make sync-console

      - name: Prepare artifacts
        run: |
          tar czvf console-dist.tar.gz console/dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: console-web-${{ github.sha }}
          path: ${{ github.workspace }}/console-dist.tar.gz
          if-no-files-found: error
          retention-days: 7

  api:
    runs-on: ubuntu-22.04
    needs: [web, console]
    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}
      - name: Cache builder
        id: api-build-cache
        uses: actions/cache@v4
        with:
          key: api-build-${{ runner.os }}-rust-${{ env.RUSTC_HASH }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            api-build-${{ runner.os }}-rust-${{ env.RUSTC_HASH }}-
            api-build-${{ runner.os }}-
            api-build-
          path: |
            api/target

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: stable
      - name: Download Landing Artifacts
        uses: actions/download-artifact@v4
        with:
          name: landing-web-${{ github.sha }}
          path: ./api
      - name: Download Console Artifacts
        uses: actions/download-artifact@v4
        with:
          name: console-web-${{ github.sha }}
          path: ./api
      - name: Extract Web Artifacts
        run: |
          mkdir -p dist/console dist/landing
          tar xzf console-dist.tar.gz -C dist/console --strip-components=2
          tar xzf landing-dist.tar.gz -C dist/landing --strip-components=2
      - name: Building APIs
        env:
          AWS_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          DISABLE_ANSI: false
          WEB_BUILD: false
          ENV: dev
          RUST_LOG: info
          DYNAMO_ENDPOINT: none
        run: |
          make docker.build
          make docker.login
          make docker.push

  deploy:
    runs-on: ubuntu-latest
    needs: [web, console, api]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy
        env:
          ENV: dev
          REGION: ap-northeast-2
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOMAIN: dev.biyard.co
        run: |
          npm i -g aws-cdk
          make deploy

  create-release-pr:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    needs: [deploy]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}
      - name: Git pr release action
        uses: grassedge/git-pr-release-action@v1.0
        with:
          base: main
          head: dev
          token: ${{ secrets.GITHUB_TOKEN }}
