name: Production deploy

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.0 --activate

      - name: Deploy to S3
        env:
          ENV: prod
          API_URL: https://api.biyard.co
          CONSOLE_URL: https://console.biyard.co
        run: |
          make sync-landing

  app:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: stable
          targets: wasm32-unknown-unknown
          cache: false

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "app-build"

      - uses: cargo-bins/cargo-binstall@main

      - name: Install Dioxus CLI
        run: cargo binstall dioxus-cli --force

      - name: Build Dioxus app
        working-directory: app
        env:
          ENV: prod
          DYNAMO_TABLE_PREFIX: biyard-prod
        run: make build

      - name: Build and push Docker image
        working-directory: app
        env:
          ENV: prod
        run: |
          make docker.login
          make docker
          make docker.push

  deploy:
    runs-on: ubuntu-latest
    needs: [web, app]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy
        env:
          ENV: prod
          REGION: ap-northeast-2
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOMAIN: biyard.co

        run: |
          npm i -g aws-cdk
          make deploy
